[phases.setup]
  nixPkgs = ["...", "php84Packages.composer"] # Railway akan mendeteksi ini otomatis

[phases.build]
  dependsOn = ["setup"]
  cmds = ["composer install --no-dev --optimize-autoloader", "npm install && npm run build"]

# Fase ini dijalankan TEPAT sebelum aplikasi start
[phases.postbuild]
  cmds = [
    "rm -rf public/storage", 
    "ln -s ../storage/app/public public/storage",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
  ]